name: Deploy to IPFS + Update Cloudflare DNSLink

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout site files
        uses: actions/checkout@v3

      - name: Upload to Storacha (IPFS)
        uses: storacha/add-to-web3@v3
        id: w3up
        with:
          path_to_add: './site'
          secret_key: ${{ secrets.W3_PRINCIPAL }}
          proof: ${{ secrets.W3_PROOF }}

      - name: Update Cloudflare DNSLink TXT Record
        run: |
          CID=${{ steps.w3up.outputs.cid }}
          ZONE_ID=${{ secrets.CLOUDFLARE_ZONE_ID }}
          RECORD_NAME=${{ secrets.CLOUDFLARE_TXT_NAME }}
          RECORD=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records?type=TXT&name=$RECORD_NAME" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: application/json")

          RECORD_ID=$(echo $RECORD | jq -r '.result[0].id')

          UPDATE_PAYLOAD=$(jq -n \
            --arg name "$RECORD_NAME" \
            --arg content "dnslink=/ipfs/$CID" \
            '{type: "TXT", name: $name, content: $content, ttl: 120}')

          curl -X PUT "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records/$RECORD_ID" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data "$UPDATE_PAYLOAD"

