name: Deploy to IPFS + Update Gandi DNSLink

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout site files
        uses: actions/checkout@v3

      - name: Upload to Storacha (IPFS)
        uses: storacha/add-to-web3@v3
        id: w3up
        with:
          path_to_add: './site'
          secret_key: ${{ secrets.W3_PRINCIPAL }}
          proof: ${{ secrets.W3_PROOF }}

      - name: Update DNSLink (_dnslink) at Gandi
        run: |
          CID=${{ steps.w3up.outputs.cid }}
          DOMAIN=${{ secrets.GANDI_DOMAIN }}
          API="https://api.gandi.net/v5/livedns/domains/$DOMAIN/records/_dnslink/TXT"
          JSON="{\"rrset_values\": [\"dnslink=/ipfs/$CID\"]}"
          curl -s -X PUT "$API" \
            -H "Authorization: Bearer ${{ secrets.GANDI_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d "$JSON"

      - name: Update DNSLink (_dnslink.www) at Gandi
        run: |
          CID=${{ steps.w3up.outputs.cid }}
          DOMAIN=${{ secrets.GANDI_DOMAIN }}
          API="https://api.gandi.net/v5/livedns/domains/$DOMAIN/records/_dnslink.www/TXT"
          JSON="{\"rrset_values\": [\"dnslink=/ipfs/$CID\"]}"
          curl -s -X PUT "$API" \
            -H "Authorization: Bearer ${{ secrets.GANDI_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d "$JSON"
