name: Deploy to IPFS via Storacha

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout site files
        uses: actions/checkout@v3

      - name: Upload to Storacha (IPFS)
        uses: storacha/add-to-web3@v3
        id: w3up
        with:
          path_to_add: './site'
          secret_key: ${{ secrets.W3_PRINCIPAL }}
          proof: ${{ secrets.W3_PROOF }}
        
      # use the outputs in subsequent steps
      - name: New CID
        run: echo ${{ steps.w3up.outputs.cid }}
        
      - name: New url
        run: echo ${{ steps.w3up.outputs.url }}
